"""new

Revision ID: b1003113d9c2
Revises: 
Create Date: 2024-12-29 01:10:08.918215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1003113d9c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Sessions', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['session_id'])

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sex', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('birth_day', sa.DateTime(), nullable=True))

    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid', sa.Boolean(), nullable=False))
        batch_op.create_foreign_key(None, 'Users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('valid')

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('birth_day')
        batch_op.drop_column('sex')
        batch_op.drop_column('description')

    with op.batch_alter_table('Sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
